### ISSUE TITLE
Controller Version Routing - sam local start-api

### ISSUE THREAD

**Issue by JouperCoding** [micronaut-projects/micronaut-aws#389]
When creating a @Controller which defines endpoints with the @Version annotation, the requests using X-API-VERSION header is not routed to the right method in a sam local start-api context. Running the same code using netty to serve the API locally works as intended

### Steps to Reproduce

1. Create a new function app
2. Create handler using RequestHandler and a Micronaut Lambda Container
3. Create a @Controller with two APIs using two versions

### Expected Behaviour

Sending X-API-VERSION header should route to the right method using @Version annotation

### Actual Behaviour

Always routes to first matched method.

### Environment Information

- **Operating System**: WIN 10
- **Micronaut Version:** 2.0
- **JDK Version:** Amazon Coretto 8

### Example Code

	@Get("/ping")
	public String pingV1() {
		log.info("Received a ping.");
		return "pong";
	}

	@Version("2")
	@Get("/ping")
	public String pingV2() {
		log.info("Received a ping.");
		return "pong v2";
	}

**Comment by ilopmar** [comment]
@JouperCoding can you please provide an sample `sam.yaml` file and the `sam` command you use to start the app?

**Comment by JouperCoding** [comment]
Looks like you were able to resolve this before I had a chance to respond :)

Quick question, when can I expect this fix to be release in 2.0.0?

Thanks!

**Comment by ilopmar** [comment]
@JouperCoding Well, I wasn't able to test it on sam-local, only on tests, so it would be great if you can provide the yaml template.

We need to discuss a few things about this issue before releasing micronaut-aws 2.0.1 but in the meantime you can try the 2.0.1.BUILD-SNAPSHOT version.

**Comment by JouperCoding** [comment]
@ilopmar Im using the following saml yaml template. and im running 

gradlew.bat build && sam local start-api -t public-api.yaml


```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Private API (Client <-> Server)
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  PublicApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.handlers.PublicApiHandler
      Runtime: java8
      CodeUri: build/exploded
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Tracing: Active
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  PublicApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: PublicApi
```

I will try the 2.0.1.BUILD-SNAPSHOT today! thanks

**Comment by ilopmar** [comment]
@JouperCoding I'm confused. I though you were using the Api Proxy Gateway approach with normal Micronaut `@Controller` in your application. I've tested this issue following this approach and I don't have any "Handler" class. This is the only class in my project:
```java
@Controller
public class PingController {

    @Get("/ping")
    public String pingV1() {
        return "pong v1";
    }

    @Version("2")
    @Get("/ping")
    public String pingV2() {
        return "pong v2";
    }
}
```

Can you please show me the content of `example.handlers.PublicApiHandler`?

**Comment by JouperCoding** [comment]
Hey, 

As a mentioned above i have two ways to run this application. The real way is using the PublicApiHandler + SAM local to test

1. The real handler is the PublicApiHandler which i have attached below. Using this handler @Version does not work when sending requests with the Version header.

2. The second dev runtime i have is a simple Micronaut.run() application.java class. This one is using netty to serve my APIs. With this approach @Version works as intended.


Here is the Lambda handler which im working with that does not have @Version support when serving my APIs.
```

import com.amazonaws.serverless.exceptions.ContainerInitializationException;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestStreamHandler;
import io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import portal.analytics.properties.AnalyticsProperties;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class PublicApiHandler implements RequestStreamHandler {
	private static Logger log = LoggerFactory.getLogger(PublicApiHandler.class);
	private static MicronautLambdaContainerHandler handler;

	public PublicApiHandler(){
		try {
			handler = new MicronautLambdaContainerHandler();
			handler.getApplicationContext().getBean(AnalyticsProperties.class).currentSettings();
		} catch (ContainerInitializationException e) {
			log.error(e.getMessage());
		}
	}

	@Override
	public void handleRequest(InputStream input, OutputStream output, Context context) throws IOException {
		handler.proxyStream(input, output, context);
	}
}

```

**Comment by ilopmar** [comment]
@JouperCoding I've released `micronaut-aws:2.0.1` that include the fix.

**Comment by JouperCoding** [comment]
Perfect! Will take a look at it this week!

**Comment by JouperCoding** [comment]
Hello,

It looks like this is still an issue. I have updated to Micronaut 2.0.1 and when i Invoke my /api/ping endpoint you can see its printing the X-API-VERSION header as 2 but printing out recived ping v1. This is still only an issue when running this in docker via the sam local-api.

![image](https://user-images.githubusercontent.com/4056655/89549385-8622ff80-d808-11ea-8d27-196ce046a926.png)

I have also verified that my application properties has this enabled.
![image](https://user-images.githubusercontent.com/4056655/89549597-cc785e80-d808-11ea-8cdc-b15d54cb9fe3.png)

Any idea's why this still is an issue?

**Comment by ilopmar** [comment]
This is the test application I was using https://github.com/micronaut-core-issues-test-app/issue-aws-389. I've committed my changes and updated to Micronaut 2.0.1.

Take a look at the controller and the tests.

**Comment by JouperCoding** [comment]
Hey @ilopmar,

There are alot of details missing from that test application. I created a fork with the sam template and some instruction for setting it up. Please try running my project https://github.com/JouperCoding/issue-aws-389 using Docker + SAM to locally run the API.

**Comment by ilopmar** [comment]
I've tried with your application and it works ok for me:

![DeepinScreenshot_select-area_20200807095944](https://user-images.githubusercontent.com/559192/89623345-c0d27980-d894-11ea-8998-56b1a066bf2f.png)

Please notice that I'm using you latest commit https://github.com/JouperCoding/issue-aws-389/commit/2e90829d31051fb745a86240afb6061ab5410097 (green square)

There must be something wrong on your environment.

**Comment by JouperCoding** [comment]
Morning @ilopmar 

Yup! I also got it to work just now. Seem like i had some issue with my environment. All good now! Thanks!

**Comment by ilopmar** [comment]
Excellent, glad it works for you :-)
