### ISSUE TITLE
Docker build for custom GraalVM native runtimes fails.

### ISSUE THREAD

**Issue by cero-t** [micronaut-projects/micronaut-aws#49]
When I tried `Custom GraalVM Native Runtimes` on this page, I got a warning, and the generated binary didn't contain Java Runtime.
https://micronaut-projects.github.io/micronaut-aws/latest/guide/#customRuntimes

The warning message is as follows.

```
[server:6]    classlist:  18,170.22 ms
[server:6]        (cap):   1,760.69 ms
[server:6]        setup:   4,722.97 ms
[server:6]     analysis:  44,020.50 ms
Warning: Aborting stand-alone image build. No instances are allowed in the image heap for a class that is initialized or reinitialized at image runtime: com.amazonaws.serverless.proxy.model.ContainerConfig. Try marking this class for build-time initialization with --initialize-at-build-time=com.amazonaws.serverless.proxy.model.ContainerConfig
Detailed message:
Trace: 	field io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.config

Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[server:67]    classlist:   6,628.29 ms
[server:67]        (cap):   1,597.73 ms
[server:67]        setup:   4,403.42 ms
[server:67]   (typeflow):   6,819.44 ms
[server:67]    (objects):   1,793.49 ms
[server:67]   (features):     253.99 ms
[server:67]     analysis:   9,047.10 ms
[server:67]     (clinit):     261.85 ms
[server:67]     universe:     845.08 ms
[server:67]      (parse):   1,915.63 ms
[server:67]     (inline):   2,603.30 ms
[server:67]    (compile):  15,898.98 ms
[server:67]      compile:  20,901.04 ms
[server:67]        image:     731.63 ms
[server:67]        write:     244.38 ms
[server:67]      [total]:  43,122.48 ms
Warning: Image 'server' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation).
```

When I added `--initialize-at-build-time=com.amazonaws.serverless.proxy.model` to `native-image.properties` and built again, native-image command succeeded.

### Environment

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

GraalVM 19.0.0 and 19.0.2

Docker Desktop Community 2.0.0.3

macOS Mojave 10.14.5

**Comment by cero-t** [comment]
(Just FYI)
When I use this bootstrap class instead of MicronautLambdaRuntime, no error occurs and the generated native binary works well on AWS Lambda custom runtime.
https://github.com/kencharos/try-graal-lambda/blob/master/src/main/java/my/graal/SampleCommand.java

**Comment by cero-t** [comment]
I found solutions.

1. add `--initialize-at-build-time=com.amazonaws.serverless.proxy.model` to `src/main/resources/META-INF/.../native-image.properties`, which resolves the warning while native-image command
2. add the definition of `AwsProxyRequest` to `src/main/graal/reflect.json` as follows, which resolves the problem that response body was null

before
```
}, {
  "name" : "com.amazonaws.serverless.proxy.model.AwsProxyResponse",
  "allPublicMethods" : true,
  "allDeclaredConstructors" : true
}, {
```

after
```
}, {
  "name" : "com.amazonaws.serverless.proxy.model.AwsProxyRequest",
  "allPublicMethods" : true,
  "allDeclaredConstructors" : true
}, {
  "name" : "com.amazonaws.serverless.proxy.model.AwsProxyResponse",
  "allPublicMethods" : true,
  "allDeclaredConstructors" : true
}, {
```

I'll write patches lator.

**Comment by otbe** [comment]
If I use you fix with the most current version if micronaut / micronaut cli the native image generation works, but (at least) while using SAM locally I get the following exception:
```
Invocation with requestId [e58c1a52-7ce0-1008-188e-6656620499ae] failed: com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.getContainerConfig()java.lang.NoSuchMethodError: com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.getContainerConfig()
        at com.amazonaws.serverless.proxy.internal.SecurityUtils.isValidHost(SecurityUtils.java:63)
        at io.micronaut.function.aws.proxy.MicronautAwsProxyRequest.getUri(MicronautAwsProxyRequest.java:167)
        at io.micronaut.http.HttpRequest.getPath(HttpRequest.java:85)
        at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:79)
        at io.micronaut.function.aws.proxy.MicronautRequestReader.readRequest(MicronautRequestReader.java:48)
        at io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler.proxy(AbstractLambdaContainerHandler.java:204)
        at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:129)
        at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:75)
```

Any ideas? Thank you!

**Comment by graemerocher** [comment]
@otbe that looks like a version conflict with the version of AWS serverless container that Micronaut uses?

**Comment by otbe** [comment]
@graemerocher Im not quite sure and I dont know how to verify that properly 🤔

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-aws/commit/0e9439dfca5e018130d716e43d20cbc640322889

**Comment by otbe** [comment]
Hi @graemerocher 

sorry for posting this in an closed issue but I think theres still a problem.
I upgraded `micronaut-function-aws-custom-runtime` and `micronaut-function-aws-api-proxy` to 1.3.1 which should inc lude all the fixed related to Graal, but no I get this error while using `sam local`

```
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received: 
```
(there is nothing after "Response received")
<img width="516" alt="Screenshot 2019-10-01 at 13 21 18" src="https://user-images.githubusercontent.com/3391052/65957911-61beff80-e44e-11e9-9c96-63667e6b164d.png">

**Comment by graemerocher** [comment]
@otbe could you provide an example that reproduces the issue?

**Comment by otbe** [comment]
Hi @graemerocher 

first things first, there is an error while building the native image that says (I totally overlooked this one in the first place):
```
Warning: Aborting stand-alone image build. com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of io.micronaut.function.aws.proxy.model.factory.MicronautAwsProxyResponseFactory are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Detailed message:
Trace: 
        at parsing io.micronaut.http.HttpResponse.notFound(HttpResponse.java:102)
Call path from entry point to io.micronaut.http.HttpResponse.notFound(): 
        at io.micronaut.http.HttpResponse.notFound(HttpResponse.java:102)
        at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1783)
        at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1761)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

In order to make sure that it isnt related to my project I created a new one with the following steps:

1. `$ mn create-app com.bar --features aws-api-gateway-graal -l kotlin -b maven` (latest mn verison)
2. update the micronat-aws-* dependency versions to 1.3.1
3. `$ mvn install`
4. and finally`$ ./sam-local.sh`. 

That causes the mentioned error whiule building the native image and the invalid response.

**Comment by otbe** [comment]
Hi @graemerocher 
1.3.2 fixes the build issue but theres still a runtime issue for me:
```
{
  "errorMessage": "io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.getAwsProxyHandler(io.micronaut.context.ApplicationContextBuilder)"
}
Function returned an invalid response (must include one of: body, headers, multiValueHeaders or statusCode in the response object). Response received:
```

I pushed my little test project, so you can have a look: https://github.com/otbe/micronaut-aws-graal-example but like already mentioned its just the CLI generated project + new dependency versions https://github.com/otbe/micronaut-aws-graal-example/blob/master/pom.xml#L46

**Comment by graemerocher** [comment]
@otbe Thanks will take a look

**Comment by graemerocher** [comment]
The underlying error appears to be 

```
java.lang.NoClassDefFoundError: Could not initialize class io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:214)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:112)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:77)
Request loop failed with: Could not initialize class io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler
```

Which is very odd since the example at https://github.com/awslabs/aws-serverless-java-container/tree/micronaut/samples/micronaut/pet-store works

**Comment by graemerocher** [comment]
Exception occurs without Graal to but provides more detail:

```
java -cp target/foo-0.1.jar io.micronaut.function.aws.runtime.MicronautLambdaRuntime
java.lang.NoClassDefFoundError: io/micronaut/function/aws/MicronautLambdaContext
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:112)
	at io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:77)
Caused by: java.lang.ClassNotFoundException: io.micronaut.function.aws.MicronautLambdaContext
```

**Comment by graemerocher** [comment]
Issue is in the dependencies. You have to use

```
    <dependency>
        <groupId>io.micronaut</groupId>
        <artifactId>micronaut-function-aws</artifactId>
        <version>1.3.2</version>
    </dependency>
```

**Comment by otbe** [comment]
That fixed it ! Thank you very much 👍 Just for clarification, my pom looks like this:
```
 <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-function-aws</artifactId>
            <version>1.3.2</version>
        </dependency>

        <dependency>
            <groupId>io.micronaut.aws</groupId>
            <artifactId>micronaut-function-aws-custom-runtime</artifactId>
            <scope>compile</scope>
            <version>1.3.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.module</groupId>
                    <artifactId>jackson-module-afterburner</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.micronaut.aws</groupId>
            <artifactId>micronaut-function-aws-api-proxy</artifactId>
            <scope>compile</scope>
            <version>1.3.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.module</groupId>
                    <artifactId>jackson-module-afterburner</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I guess this needs to be fixed in the CLI project template as well? Maybe I can provide a PR somewhere?

**Comment by graemerocher** [comment]
The fix is actually to update the Micronaut BOM which has already been updated. It will be fixed in Micronaut 1.2.4 when that is released (probably this week)
